---
  personal_homebrew_github_api_token: 
  personal_aws_access_key_id: 
  personal_aws_secret_access_key: 
  personal_git_name: 
  personal_git_email: 
  persobal_ssh_private_key: 
  persobal_ssh_public_key: 
  personal_restore_time_machine: 
  personal_time_machine_root: 
  personal_time_machine_directories:
